name: Go Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create Go package directory
      run: mkdir -p /home/runner/go/pkg/mod
      
   - name: Setup Go
      uses: actions/setup-go@v5
      with:
        cache: true
        cache-dependency-path: |
          **/go.mod
          **/go.sum
