name: Your Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22x
        cache: true
        cache-dependency-path: |
          **/go.mod
          **/go.sum
          
    - name: Build
      run: go build -v ./...

    # other job steps...
