name: Go Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.16.x
        cache: true

    - name: Download Go modules
      run: go mod download
      working-directory: ./path/to/your/go/project

    # Rest of your steps...
