name: Go Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clear Go dependencies directory
      run: rm -rf ${{ github.workspace }}/go/pkg/mod

    - name: Cache Go dependencies
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x

    - name: Download dependencies
      run: go mod download

    - name: Run Go command
      run: go version
