name: Go Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear conflicting directory
        run: rm -rf ${{ github.workspace }}/../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64

      - name: Extract tar file
        run: /usr/bin/tar -xf /setup-go-Test

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum

      - name: Run Go command
        run: go version
